
export const sample_foods: any[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Margherita Pizza',
    cookTime: '12-18',
    price: 12,
    favorite: false,
    origins: ['italy'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '3',
    name: 'Spinach and Mushroom Quesadilla',
    cookTime: '15-20',
    price: 9,
    favorite: true,
    origins: ['mexico'],
    stars: 4.4,
    imageUrl: 'assets/food-3.jpeg',
    tags: ['FastFood', 'Mexican', 'Lunch'],
  },
  {
    id: '4',
    name: 'Vegetarian Sushi Roll',
    cookTime: '20-25',
    price: 15,
    favorite: false,
    origins: ['japan'],
    stars: 4.6,
    imageUrl: 'assets/food-4.jpeg',
    tags: ['SlowFood', 'Sushi', 'Lunch'],
  },
  {
    id: '5',
    name: 'Eggplant Parmesan',
    cookTime: '25-30',
    price: 18,
    favorite: true,
    origins: ['italy'],
    stars: 4.8,
    imageUrl: 'assets/food-5.jpeg',
    tags: ['SlowFood', 'Italian', 'Dinner'],
  },
  {
    id: '6',
    name: 'Vegetable Curry',
    cookTime: '30-35',
    price: 14,
    favorite: false,
    origins: ['india'],
    stars: 4.5,
    imageUrl: 'assets/food-6.jpeg',
    tags: ['SlowFood', 'Curry', 'Dinner'],
  },
  {
    id: '7',
    name: 'Caprese Salad',
    cookTime: '10-15',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.3,
    imageUrl: 'assets/food-7.jpeg',
    tags: ['FastFood', 'Salad', 'Lunch'],
  },
  {
    id: '8',
    name: 'Vegetable Lasagna',
    cookTime: '35-40',
    price: 20,
    favorite: true,
    origins: ['italy'],
    stars: 4.9,
    imageUrl: 'assets/food-8.jpeg',
    tags: ['SlowFood', 'Italian', 'Dinner'],
  },
  {
    id: '9',
    name: 'Falafel Wrap',
    cookTime: '15-20',
    price: 8,
    favorite: false,
    origins: ['middle east'],
    stars: 4.2,
    imageUrl: 'assets/food-9.jpeg',
    tags: ['FastFood', 'Wrap', 'Lunch'],
  },
  {
    id: '10',
    name: 'Vegetable Pad Thai',
    cookTime: '20-25',
    price: 16,
    favorite: true,
    origins: ['thailand'],
    stars: 4.6,
    imageUrl: 'assets/food-10.jpeg',
    tags: ['SlowFood', 'Thai', 'Dinner'],
  },
  {
    id: '11',
    name: 'Mushroom Risotto',
    cookTime: '30-35',
    price: 22,
    favorite: true,
    origins: ['italy'],
    stars: 4.7,
    imageUrl: 'assets/food-11.jpeg',
    tags: ['SlowFood', 'Italian', 'Dinner'],
  },
]

export const sample_tags:any[] = [
    { name: 'All', count: 6 },
    { name: 'FastFood', count: 4 },
    { name: 'Pizza', count: 2 },
    { name: 'Lunch', count: 3 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 1 },
    { name: 'Soup', count: 1 },
  ]
  
  export const sample_users: any[] = [
    {
      name: 'Patel Priyanshu',
      email: 'priyanshu@gmail.com',
      password: '1234',
      address: 'Toronto On',
      isAdmin: true,
    },
    {
      name: 'Akki Patel',
      email: 'Akki@gmail.com',
      password: '1234',
      address: 'Shanghai',
      isAdmin: false,
    },
  ];